// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/index.get').default>>>>
    }
    '/api/auth': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/index.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/automations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automations/[id].delete').default>>>>
    }
    '/api/automations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automations/index.post').default>>>>
    }
    '/api/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calendar/index.get').default>>>>
    }
    '/api/projects/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].put').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index.post').default>>>>
    }
    '/api/reminders/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/[id].delete').default>>>>
    }
    '/api/reminders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/index.post').default>>>>
    }
    '/api/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.put').default>>>>
    }
    '/api/tags/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/[id].delete').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.post').default>>>>
    }
    '/api/tasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].put').default>>>>
    }
    '/api/tasks/:id/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/complete.post').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/api/tasks/move': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/move.post').default>>>>
    }
    '/api/templates/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/[id].delete').default>>>>
    }
    '/api/templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/index.post').default>>>>
    }
    '/api/time-entries/active': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/time-entries/active.get').default>>>>
    }
    '/api/time-entries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/time-entries/index.get').default>>>>
    }
    '/api/time-entries/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/time-entries/start.post').default>>>>
    }
    '/api/time-entries/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/time-entries/stop.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}